HRManagementSystem.UI/Controllers/AdvertisementController.cs
using HRManagementSystem.Business.Interfaces;
using HRManagementSystem.Common.Enums;
using HRManagementSystem.Dtos;
using HRManagementSystem.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace HRManagementSystem.UI.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly IAppUserService _appUserService;
        private readonly IAdvertisementAppUserService _advertisementAppUserService;

        public AdvertisementController(IAppUserService appUserService, IAdvertisementAppUserService advertisementAppUserService)
        {
            _appUserService = appUserService;
            _advertisementAppUserService = advertisementAppUserService;
        }


        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Send(int advertisementId)
        {
            var userId = int.Parse((User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)).Value);
            var userResponse = await _appUserService.GetByIdAsync<AppUserListDto>(userId);

            ViewBag.GenderId = userResponse.Data.GenderId;

            var items = Enum.GetValues(typeof(MilitaryStatusType));

            var list = new List<MilitaryStatusListDto>();

            foreach (int item in items)
            {
                list.Add(new MilitaryStatusListDto
                {
                    Id = item,
                    Definition = Enum.GetName(typeof(MilitaryStatusType), item),
                });
            }

            ViewBag.MilitaryStatus = new SelectList(list, "Id", "Definition");

            return View(new AdvertisementAppUserCreateModel
            {
                AdvertisementId = advertisementId,
                AppUserId = userId,
            });
        }


        [Authorize(Roles = "Member")]
        [HttpPost]
        public async Task<IActionResult> Send(AdvertisementAppUserCreateModel model)
        {
            AdvertisementAppUserCreateDto dto = new();
            if (model.CvFile != null)
            {
                var fileName = Guid.NewGuid().ToString();
                var extName = Path.GetExtension(model.CvFile.FileName);
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "cvFiles", fileName + extName);
                var stream = new FileStream(path, FileMode.Create);
                await model.CvFile.CopyToAsync(stream);
                dto.CvPath = path;
            }

            dto.AdvertisementAppUserStatusId = model.AdvertisementAppUserStatusId;
            dto.AdvertisementId = model.AdvertisementId;
            dto.AppUserId = model.AppUserId;
            dto.EndDate = model.EndDate;
            dto.MilitaryStatusId = model.MilitaryStatusId;
            dto.WorkExperience = model.WorkExperience;

            var response = await _advertisementAppUserService.CreateAsync(dto);
            if (response.ResponseType == Common.Objects.ResponseType.ValidationError)
            {
                foreach (var error in response.ValidationErrors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }

                var userId = int.Parse((User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)).Value);
                var userResponse = await _appUserService.GetByIdAsync<AppUserListDto>(userId);

                ViewBag.GenderId = userResponse.Data.GenderId;

                var items = Enum.GetValues(typeof(MilitaryStatusType));

                var list = new List<MilitaryStatusListDto>();

                foreach (int item in items)
                {
                    list.Add(new MilitaryStatusListDto
                    {
                        Id = item,
                        Definition = Enum.GetName(typeof(MilitaryStatusType), item),
                    });
                }

                ViewBag.MilitaryStatus = new SelectList(list, "Id", "Definition");

                return View(model);
            }
            else
            {
                return RedirectToAction("HumanResources", "Home");
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Applied);
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SetStatus(int advertisementAppUserId, AdvertisementAppUserStatusType type)
        {
            await _advertisementAppUserService.SetStatusAsync(advertisementAppUserId, type);
            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ApprovedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Interview);
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RejectedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Negative);
            return View();
        }
    }
}

HRManagementSystem.UI/Controllers/ApplicationController.cs
using HRManagementSystem.Business.Interfaces;
using HRManagementSystem.Dtos;
using HRManagementSystem.UI.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HRManagementSystem.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ApplicationController : Controller
    {
        private readonly IAdvertisementService _advertisementService;

        public ApplicationController(IAdvertisementService advertisementService)
        {
            _advertisementService = advertisementService;
        }

        public async Task<IActionResult> List()
        {
            var response = await _advertisementService.GetAllAsync();
            return this.ResponseView(response);
        }

        public IActionResult Create()
        {
            return View(new AdvertisementCreateDto());
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdvertisementCreateDto dto)
        {
            var response = await _advertisementService.CreateAsync(dto);
            return this.ResponseRedirectAction(response, "List");
        }

        public async Task<IActionResult> Update(int id)
        {
            var response = await _advertisementService.GetByIdAsync<AdvertisementUpdateDto>(id);
            return this.ResponseView(response);
        }

        [HttpPost]
        public async Task<IActionResult> Update(AdvertisementUpdateDto dto)
        {
            var response = await _advertisementService.UpdateAsync(dto);
            return this.ResponseRedirectAction(response, "List");
        }

        public async Task<IActionResult> Remove(int id)
        {
            var response = await _advertisementService.RemoveAsync(id);
            return this.ResponseRedirectAction(response, "List");
        }

    }
}

HRManagementSystem.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>HR Management System</title>
    <link rel="stylesheet" href="~/FocusAdminTemplate/vendor/owl-carousel/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/FocusAdminTemplate/vendor/owl-carousel/css/owl.theme.default.min.css">
    <link href="~/FocusAdminTemplate/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/focusadmintemplate/css/perfect-scrollbar.css" rel="stylesheet" />
    <link href="~/focusadmintemplate/css/style.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    @RenderSection("css", false)
</head>

<body>
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>

    <div id="main-wrapper">

        <div class="nav-header">
            <a asp-action="Index" asp-controller="Home" class="brand-logo">
                HRMS
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            <div class="search_bar dropdown">
                                <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <div class="dropdown-menu p-0 m-0">
                                    <form>
                                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                                    </form>
                                </div>
                            </div>
                        </div>

                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown notification_dropdown">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="quixnav">
            <div class="quixnav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label first text-light">@(User.Identity.IsAuthenticated && User.IsInRole("Admin") ? "Admin" : "") Panel</li>
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Member"))
                            {
                                <li>
                                    <a asp-action="HumanResources" asp-controller="Home" aria-expanded="false">
                                        <i class="fa-brands fa-web-awesome"></i><span class="nav-text">Job Adverts</span>
                                    </a>
                                </li>
                            }

                            @if (User.IsInRole("Admin"))
                            {
                                <li>
                                    <a asp-action="List" asp-controller="Advertisement" aria-expanded="false">
                                        <i class="fa-brands fa-uikit"></i><span class="nav-text">Applications</span>
                                    </a>
                                </li>

                                <li>
                                    <a asp-action="List" asp-controller="Application" aria-expanded="false">
                                        <i class="fa-brands fa-space-awesome"></i><span class="nav-text">Advertisements</span>
                                    </a>
                                </li>
                            }
                            <li>
                                <a asp-action="LogOut" asp-controller="Account" aria-expanded="false">
                                    <i class="fa-solid fa-right-from-bracket"></i><span class="nav-text">Log Out</span>
                                </a>
                            </li>

                        }
                        else
                        {
                            <li>
                                <a asp-action="SignUp" asp-controller="Account" aria-expanded="false">
                                    <i class="fa-solid fa-user-plus"></i><span class="nav-text">Sign Up</span>
                                </a>
                            </li>
                            <li>
                                <a asp-action="SignIn" asp-controller="Account" aria-expanded="false">
                                    <i class="fa-solid fa-right-to-bracket"></i><span class="nav-text">Login</span>
                                </a>
                            </li>

                            <li>
                                <a asp-action="HumanResources" asp-controller="Home" aria-expanded="false">
                                    <i class="fa-solid fa-person"></i><span class="nav-text">Human Resources</span>
                                </a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    <!--Content-->
    <div class="content-body">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>

    <!--Footer-->
    <div class="footer">
        <div class="copyright">
            <p>HR Management System | @DateTime.Now.Year</p>
        </div>
    </div>

    <!--Scripts-->
    <script src="~/FocusAdminTemplate/vendor/global/global.min.js"></script>
    <script src="~/FocusAdminTemplate/js/quixnav-init.js"></script>
    <script src="~/FocusAdminTemplate/js/custom.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/raphael/raphael.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/morris/morris.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/gaugeJS/dist/gauge.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/flot/jquery.flot.js"></script>
    <script src="~/FocusAdminTemplate/vendor/flot/jquery.flot.resize.js"></script>
    <script src="~/FocusAdminTemplate/vendor/owl-carousel/js/owl.carousel.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/jqvmap/js/jquery.vmap.min.js"></script>
    <script src="~/FocusAdminTemplate/vendor/jqvmap/js/jquery.vmap.usa.js"></script>
    <script src="~/FocusAdminTemplate/vendor/jquery.counterup/jquery.counterup.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/FocusAdminTemplate/js/dashboard/dashboard-1.js"></script>

    <!-- Render section -->
    @RenderSection("script", false)
</body>
</html>